Exception in thread Thread-4:
Traceback (most recent call last):
  File "/data/qtran/anaconda3/envs/medqa/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/data/qtran/anaconda3/envs/medqa/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/data/qtran/anaconda3/envs/medqa/lib/python3.8/site-packages/lightning_app/utilities/app_helpers.py", line 191, in target_fn
    from streamlit.server.server import Server
ModuleNotFoundError: No module named 'streamlit.server'
2022-09-07 10:20:32.715 Created a temporary directory at /tmp/tmp98wcr64o
2022-09-07 10:20:32.715 Writing /tmp/tmp98wcr64o/_remote_module_non_scriptable.py
Exception in thread Thread-5:
Traceback (most recent call last):
  File "/data/qtran/anaconda3/envs/medqa/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/data/qtran/anaconda3/envs/medqa/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/data/qtran/anaconda3/envs/medqa/lib/python3.8/site-packages/lightning_app/utilities/app_helpers.py", line 191, in target_fn
    from streamlit.server.server import Server
ModuleNotFoundError: No module named 'streamlit.server'
Exception in thread Thread-6:
Traceback (most recent call last):
  File "/data/qtran/anaconda3/envs/medqa/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/data/qtran/anaconda3/envs/medqa/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/data/qtran/anaconda3/envs/medqa/lib/python3.8/site-packages/lightning_app/utilities/app_helpers.py", line 191, in target_fn
    from streamlit.server.server import Server
ModuleNotFoundError: No module named 'streamlit.server'
Exception in thread Thread-7:
Traceback (most recent call last):
  File "/data/qtran/anaconda3/envs/medqa/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/data/qtran/anaconda3/envs/medqa/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/data/qtran/anaconda3/envs/medqa/lib/python3.8/site-packages/lightning_app/utilities/app_helpers.py", line 191, in target_fn
    from streamlit.server.server import Server
ModuleNotFoundError: No module named 'streamlit.server'
Exception in thread Thread-8:
Traceback (most recent call last):
  File "/data/qtran/anaconda3/envs/medqa/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/data/qtran/anaconda3/envs/medqa/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/data/qtran/anaconda3/envs/medqa/lib/python3.8/site-packages/lightning_app/utilities/app_helpers.py", line 191, in target_fn
    from streamlit.server.server import Server
ModuleNotFoundError: No module named 'streamlit.server'
